language: php

sudo: false

php:
  - 7.1
  - 7.2
  - 7.3
  - hhvm
  - nightly

before_script:
  - composer self-update
  - composer install

script:
  - ./vendor/bin/phpunit
  - if [[ "$TRAVIS_PHP_VERSION" = '7.1' ]]; then ./vendor/bin/psalm; fi
  - ./vendor/bin/phpcs

after_script:
  - sh .travis.coverage.sh

matrix:
  allow_failures:
    - php: hhvm
    - php: nightly
